version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Starting Terraform ${TF_ACTION} for ${ENVIRONMENT} environment"
  build:
    commands:
      - ./tf-${TF_ACTION}.sh ${ENVIRONMENT}
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  